behaviors:
  CNC_Cube_Pushing_Behaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048 
      buffer_size: 20480 
      learning_rate: 0.0001
      beta: 0.0075
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
      curiosity:
        strength: 0.1
        gamma: 0.8
        encoding_size: 256
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
